@api = http://localhost:3000/episodes

GET {{api}}/?limit=20
x-api-key: 123

###

GET {{api}}/aoeu-aoeu

###

POST {{api}}
Content-Type: application/json

{
  "name": "El nestJS",
  "featured": true,
  "artists": ["test", "cielo"],
  "releaseDate": "2024-09-11",
  "duration": "02:40",
  "title": "test"
}

###

PUT  {{api}}/2

{

}

###

DELETE {{api}}/2



